# permissions for end users to view backupverifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cnpg-backup-verifier
    app.kubernetes.io/managed-by: kustomize
  name: backupverifier-viewer-role
rules:
- apiGroups:
  - backupverifier.cnpg.io
  resources:
  - backupverifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backupverifier.cnpg.io
  resources:
  - backupverifiers/status
  verbs:
  - get
