---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cnpg.k8s.amoniac.eu
  resources:
  - backupverifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnpg.k8s.amoniac.eu
  resources:
  - backupverifiers/finalizers
  verbs:
  - update
- apiGroups:
  - cnpg.k8s.amoniac.eu
  resources:
  - backupverifiers/status
  verbs:
  - get
  - patch
  - update
