---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backupverifier.cnpg.io
  resources:
  - cronverifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backupverifier.cnpg.io
  resources:
  - cronverifiers/finalizers
  verbs:
  - update
- apiGroups:
  - backupverifier.cnpg.io
  resources:
  - cronverifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - backups
  - clusters
  verbs:
  - get
  - list
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - backups/status
  verbs:
  - get
