# permissions for end users to edit verifyjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cnpg-backup-verifier
    app.kubernetes.io/managed-by: kustomize
  name: verifyjob-editor-role
rules:
- apiGroups:
  - backupverifier.cnpg.io
  resources:
  - verifyjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backupverifier.cnpg.io
  resources:
  - verifyjobs/status
  verbs:
  - get
